### ISSUE TITLE
Stacking reward disappeared after several hours

### ISSUE THREAD

**Issue by andreym** [x42protocol/X42-FullNode-Old#14]
On 16:54:40, the stacking reward was credited, On 21:28:44 it disappeared from the wallet. The log extracts showing the places when reward was credited and disappeared are below. Full log is available on demand. OS: Debian GNU/Linux 9.5 (stretch)

======Wallets======
AndreyM/account 0,             Confirmed balance: 1220.00504075        Unconfirmed balance: 0.00000000

[2018-11-27 16:54:40.5356 39] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CreateCoinstakeAsync>d__44.MoveNext Node staking with 1030.48682477 (0.08 % of the network weight 1328404.46642498), est. time to find new block is 22:55:02.
[2018-11-27 16:54:41.0897 49] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CheckStakeAsync>d__42.MoveNext ==================================================================
[2018-11-27 16:54:41.0897 49] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CheckStakeAsync>d__42.MoveNext Found new POS block hash '63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7' at height 139741.
[2018-11-27 16:54:41.0919 49] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CheckStakeAsync>d__42.MoveNext ==================================================================
[2018-11-27 16:54:44.3408 11] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 11/27/2018 16:54:44
Headers.Height:      139741   Headers.Hash:     63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7
Consensus.Height:    139741   Consensus.Hash:   63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7
BlockStore.Height:   139741   BlockStore.Hash:  63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7
Wallet.Height:       139741   Wallet.Hash:      63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7

======Connection====== agent x42:1.2.9
Peer:[::ffff:142.93.143.81]:52342,       connected:outbound,        height:139647,        agent:/x42:2.0.0.5/
Peer:[::ffff:34.255.35.42]:52342,        connected:outbound,        height:139740,        agent:x42:1.2.9
Peer:[::ffff:200.7.37.202]:52342,        connected:outbound,        height:139739,        agent:x42:1.2.9
Peer:[::ffff:66.42.81.117]:52342,        connected:outbound,        height:139739,        agent:x42:1.2.9
Peer:[::ffff:52.211.235.48]:42522,       connected:outbound,        height:139647,        agent:/x42:2.0.0.5/
Peer:[::ffff:172.92.119.68]:52342,       connected:outbound,        height:139739,        agent:x42:1.2.9

======Consensus Manager======
Unconsumed blocks: -31 -- (-13,038 / 209,715,200 bytes). Cache is filled by: -0.01%

======Block Puller======
Blocks being downloaded: 0
Queueued downloads: 0
Average block size: 0.49 KB
Total download speed: 33.61 KB/sec
Average time to download a block: 14.47 ms
Amount of blocks node can download in 1 second: 69.1

======BlockStore======
Batch Size: 0 kb / 5000 kb  (0 blocks)

=======Mempool=======
MempoolSize: 0    DynamicSize: 1 kb   OrphanSize: 0   

======Wallets======
AndreyM/account 0,             Confirmed balance: 1240.00504075        Unconfirmed balance: 0.00000000

[2018-11-27 16:54:49.3437 39] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 11/27/2018 16:54:49
Headers.Height:      139741   Headers.Hash:     63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7
Consensus.Height:    139741   Consensus.Hash:   63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7
BlockStore.Height:   139741   BlockStore.Hash:  63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7
Wallet.Height:       139741   Wallet.Hash:      63971fd984326f6f4b1d831d70561cf0f1039b94a33f8844c4b9063c48bba1c7

======Connection====== agent x42:1.2.9
Peer:[::ffff:142.93.143.81]:52342,       connected:outbound,        height:139647,        agent:/x42:2.0.0.5/
Peer:[::ffff:34.255.35.42]:52342,        connected:outbound,        height:139740,        agent:x42:1.2.9
Peer:[::ffff:200.7.37.202]:52342,        connected:outbound,        height:139739,        agent:x42:1.2.9
Peer:[::ffff:66.42.81.117]:52342,        connected:outbound,        height:139739,        agent:x42:1.2.9
Peer:[::ffff:52.211.235.48]:42522,       connected:outbound,        height:139647,        agent:/x42:2.0.0.5/
Peer:[::ffff:172.92.119.68]:52342,       connected:outbound,        height:139739,        agent:x42:1.2.9

======Consensus Manager======
Unconsumed blocks: -31 -- (-13,038 / 209,715,200 bytes). Cache is filled by: -0.01%

======Block Puller======
Blocks being downloaded: 0
Queueued downloads: 0
Average block size: 0.49 KB
Total download speed: 33.61 KB/sec
Average time to download a block: 14.47 ms
Amount of blocks node can download in 1 second: 69.1

======BlockStore======
Batch Size: 0 kb / 5000 kb  (0 blocks)

=======Mempool=======
MempoolSize: 0    DynamicSize: 1 kb   OrphanSize: 0   

......................................................

======Wallets======
AndreyM/account 0,             Confirmed balance: 1240.00504075        Unconfirmed balance: 0.00000000

[2018-11-27 21:28:43.8435 36] INFO: Stratis.Bitcoin.Consensus.ConsensusManager+<RewindToForkPointAsync>d__50.MoveNext Reorg from block '139978-3366420e22e6f111c4f8626cd8cb4a518a5e8234d327b890bd60089dbcfcb1d2-FullyValidated' to '139631-a5811217ffd65fffbada4cdd7c90c266fc66caf0e74a99b7e0c6896025f7a37e-FullyValidated'
[2018-11-27 21:28:43.9526 34] INFO: Stratis.Bitcoin.Features.Wallet.WalletSyncManager+<OnProcessBlockAsync>d__16.MoveNext Reorg detected, going back from '139978-3366420e22e6f111c4f8626cd8cb4a518a5e8234d327b890bd60089dbcfcb1d2-FullyValidated' to '139631-a5811217ffd65fffbada4cdd7c90c266fc66caf0e74a99b7e0c6896025f7a37e-FullyValidated'.
[2018-11-27 21:28:44.1473 22] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 11/27/2018 21:28:44
Headers.Height:      139856   Headers.Hash:     825ee375a3a75e6f2492932b032d1220a780aaba5ee75d277ae22c1c2fa8a081
Consensus.Height:    139708   Consensus.Hash:   6e7926e37e56ed96a5b2c6de6699466db30255de5f75e795f47ee3a0a3d01038
BlockStore.Height:   139978   BlockStore.Hash:  3366420e22e6f111c4f8626cd8cb4a518a5e8234d327b890bd60089dbcfcb1d2
Wallet.Height:       139708   Wallet.Hash:      6e7926e37e56ed96a5b2c6de6699466db30255de5f75e795f47ee3a0a3d01038

======Connection====== agent x42:1.2.9
Peer:[::ffff:142.93.143.81]:52342,       connected:outbound,        height:139856,        agent:/x42:2.0.0.5/
Peer:[::ffff:34.255.35.42]:52342,        connected:outbound,        height:139977,        agent:x42:1.2.9
Peer:[::ffff:200.7.37.202]:52342,        connected:outbound,        height:139856,        agent:x42:1.2.9
Peer:[::ffff:66.42.81.117]:52342,        connected:outbound,        height:139978,        agent:x42:1.2.9
Peer:[::ffff:52.211.235.48]:42522,       connected:outbound,        height:139856,        agent:/x42:2.0.0.5/
Peer:[::ffff:172.92.119.68]:52342,       connected:outbound,        height:139979,        agent:x42:1.2.9

======Consensus Manager======
Unconsumed blocks: 192 -- (100,970 / 209,715,200 bytes). Cache is filled by: 0.05%

======Block Puller======
Blocks being downloaded: 0
Queueued downloads: 0
Average block size: 0.45 KB
Total download speed: 65.28 KB/sec
Average time to download a block: 6.95 ms
Amount of blocks node can download in 1 second: 143.99

======BlockStore======
Batch Size: 40 kb / 5000 kb  (77 blocks)

=======Mempool=======
MempoolSize: 6    DynamicSize: 8 kb   OrphanSize: 0   

======Wallets======
AndreyM/account 0,             Confirmed balance: 1220.00504075        Unconfirmed balance: 0.00000000

[2018-11-27 21:28:44.7918 31] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CreateCoinstakeAsync>d__44.MoveNext Node staking with 1220.00504075 (0.09 % of the network weight 1374053.55775101), est. time to find new block is 20:01:21.
[2018-11-27 21:28:48.8007 48] INFO: Stratis.Bitcoin.Features.Miner.Staking.PosMinting+<CreateCoinstakeAsync>d__44.MoveNext Node staking with 1220.00504075 (0.09 % of the network weight 1374053.55775101), est. time to find new block is 20:01:21.
[2018-11-27 21:28:49.1499 48] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0 ======Node stats====== 11/27/2018 21:28:49
Headers.Height:      139856   Headers.Hash:     825ee375a3a75e6f2492932b032d1220a780aaba5ee75d277ae22c1c2fa8a081
Consensus.Height:    139856   Consensus.Hash:   825ee375a3a75e6f2492932b032d1220a780aaba5ee75d277ae22c1c2fa8a081
BlockStore.Height:   139856   BlockStore.Hash:  825ee375a3a75e6f2492932b032d1220a780aaba5ee75d277ae22c1c2fa8a081
Wallet.Height:       139856   Wallet.Hash:      825ee375a3a75e6f2492932b032d1220a780aaba5ee75d277ae22c1c2fa8a081

======Connection====== agent x42:1.2.9
Peer:[::ffff:142.93.143.81]:52342,       connected:outbound,        height:139856,        agent:/x42:2.0.0.5/
Peer:[::ffff:34.255.35.42]:52342,        connected:outbound,        height:139977,        agent:x42:1.2.9
Peer:[::ffff:200.7.37.202]:52342,        connected:outbound,        height:139856,        agent:x42:1.2.9
Peer:[::ffff:66.42.81.117]:52342,        connected:outbound,        height:139978,        agent:x42:1.2.9
Peer:[::ffff:52.211.235.48]:42522,       connected:outbound,        height:139856,        agent:/x42:2.0.0.5/
Peer:[::ffff:172.92.119.68]:52342,       connected:outbound,        height:139979,        agent:x42:1.2.9

======Consensus Manager======
Unconsumed blocks: -33 -- (-13,842 / 209,715,200 bytes). Cache is filled by: -0.01%

======Block Puller======
Blocks being downloaded: 0
Queueued downloads: 0
Average block size: 0.45 KB
Total download speed: 65.28 KB/sec
Average time to download a block: 6.95 ms
Amount of blocks node can download in 1 second: 143.99

======BlockStore======
Batch Size: 0 kb / 5000 kb  (0 blocks)

=======Mempool=======
MempoolSize: 0    DynamicSize: 2 kb   OrphanSize: 0

**Comment by Igor-san** [comment]
Yep, Reorg detected, going back from - and the daily work is gone :(

**Comment by DennisAMenace** [comment]
This has been resolved.
